### ISSUE TITLE
Error on /Chapter07/hillar_django_restful_07_03/restful01/drones/views.py

### ISSUE THREAD

**Issue by fdimarh** [PacktPublishing/Django-RESTful-Web-Services#2]
There is a trouble on this code and i've trace the error and found on this class CompetitionFilter(filters.FilterSet):
and the error generate this output
TypeError at /competitions/

__init__() got an unexpected keyword argument 'name'

**Comment by Pomax** [comment]
`name` should actually be `field_name`:

```python
class CompetitionFilter(FilterSet): 
    from_achievement_date = DateTimeFilter( 
        field_name='distance_achievement_date', lookup_expr='gte') 
    to_achievement_date = DateTimeFilter( 
        field_name='distance_achievement_date', lookup_expr='lte') 
    min_distance_in_feet = NumberFilter( 
        field_name='distance_in_feet', lookup_expr='gte') 
    max_distance_in_feet = NumberFilter( 
        field_name='distance_in_feet', lookup_expr='lte') 
    drone_name = AllValuesFilter( 
        field_name='drone__name') 
    pilot_name = AllValuesFilter( 
        field_name='pilot__name') 
 
    class Meta: 
        model = Competition 
        fields = ( 
            'distance_in_feet', 
            'from_achievement_date', 
            'to_achievement_date', 
            'min_distance_in_feet', 
            'max_distance_in_feet', 
            # drone__name will be accessed as drone_name 
            'drone_name', 
            # pilot__name will be accessed as pilot_name 
            'pilot_name', 
            )
```

but also see https://github.com/PacktPublishing/Django-RESTful-Web-Services/issues/3 because the `FilterSet` import needs to come from `django_filters`, not `rest_framework`

**Comment by Gabkings** [comment]
Same - the reason is that FilterSet is part of django_filters, not rest_framekwork, so:

...
# remove the "from rest_framework import filters" line
...
from django_filters import FilterSet, AllValuesFilter, DateTimeFilter, NumberFilter 

class CompetitionFilter(FilterSet)

**Comment by Pomax** [comment]
@deepesh-packt did a PR fix this? If not, this is still going to cause problems for people following along with the text
