### ISSUE TITLE
AttributeError: module 'rest_framework.filters' has no attribute 'FilterSet'

### ISSUE THREAD

**Issue by yslhzj** [PacktPublishing/Django-RESTful-Web-Services#3]
I was practicing Chapter08. 
When I run the program Times the following error, please help fix it, thank you. 

AttributeError: module restore _ framework.filters' has no attribute extension FilterSet' 

Relevant information: 
Djaog 1.11.11. 
Python 3.6. 
Djangorestframework-3.6.4

**Comment by Pomax** [comment]
Same - the reason is that FilterSet is part of `django_filters`, not `rest_framekwork`, so:
```
...
# remove the "from rest_framework import filters" line
...
from django_filters import FilterSet, AllValuesFilter, DateTimeFilter, NumberFilter 

... 

class CompetitionFilter(FilterSet): 
  ...
```

**Comment by Pomax** [comment]
@deepesh-packt did a PR fix this? If not, this is still going to cause problems for people following along with the text

**Comment by josmare** [comment]
I kept playing until I got the correct references from here: 

[Here](https://django-filter.readthedocs.io/en/stable/guide/rest_framework.html
)

The correct import in Views.py is like this: 

`from django_filters import rest_framework as filters
`

and the code for  `CompetitionFilter`is like this

`min_distance_in_feet = filters.NumberFilter(
        field_name='distance_in_feet', lookup_expr='gte')
 max_distance_in_feet = filters.NumberFilter(
        field_name='distance_in_feet', lookup_expr='lte')
`

**Comment by Ehsan-sudo** [comment]
> I kept playing until I got the correct references from here: 
> 
> [Here](https://django-filter.readthedocs.io/en/stable/guide/rest_framework.html
> )
> 
> The correct import in Views.py is like this: 
> 
> `from django_filters import rest_framework as filters
> `
> 
> and the code for  `CompetitionFilter`is like this
> 
> `min_distance_in_feet = filters.NumberFilter(
>         field_name='distance_in_feet', lookup_expr='gte')
>  max_distance_in_feet = filters.NumberFilter(
>         field_name='distance_in_feet', lookup_expr='lte')
> `
> 

It worked for me! I was using "name" instead of "field_name" which caused the problem.

**Comment by carlosdelfino** [comment]
I was having success adapting the contents of the book up to chapter 7, for django 4.1.5 and Python 3.10.6 when I ran into this same problem. I made the adjustments suggested here until my comment, but I see that the CompetitionFilter class is not having an effect, I tried to access the URL: http://localhost:8000/drones/competitions/?pilot_name=Penelope+Pitstop&drone_name=WonderDrone and all competitions are returned. 

my code is available at: https://github.com/carlosdelfino/Django-RESTful-Web-Services

**Comment by carlosdelfino** [comment]
I found the solution to the problem, follow the path performed:

https://github.com/carlosdelfino/Django-RESTful-Web-Services/commit/76bfbfc5e9fa19fa4f8055e331503fbf6142b38a

**Comment by Pomax** [comment]
If you've forked the repo and updated the code to work, remember to file a PR so that the official repository can be updated, instead of telling people to use your repository.

**Comment by PaulPextra** [comment]
Please, also remember to rename **_"filter_fields"_** to **_"filterset_fields"_** in the classes with the _**List**_ suffix (_DroneCategoryList_, _DroneList_, and _PilotList_), else request with filter query parameter will always return list of all the objects.

**Comment by smlnjoroge** [comment]
from django_filters import FilterSet, AllValuesFilter, DateTimeFilter, NumberFilter
from django_filters import rest_framework as filters
